version: "3.0"

services:
  openresty:
    build: ./nginx/
    ports:
      - "8090:80"
    networks:
      - app
  app_container_1:
    build: .
    container_name: "app_container_1"
    networks:
      - app

  app_container_2:
    build: .
    container_name: "app_container_2"
    networks:
      - app

  app_container_3:
    build: .
    container_name: "app_container_3"
    networks:
      - app

  app_container_4:
    build: .
    container_name: "app_container_4"
    networks:
      - app

networks:
  app:
